// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwmlitxnassxgbcyoyzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3bWxpdHhuYXNzeGdiY3lveXpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDE1MDIsImV4cCI6MjA3NDQ3NzUwMn0.lcuMwjK230X85JCpzmmsvDImQowTdP4vNUqVY8pYyHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});